namespace SqlNado;

public enum SQLiteDatabaseConfiguration
{
    SQLITE_DBCONFIG_MAINDBNAME = 1000,
    SQLITE_DBCONFIG_LOOKASIDE = 1001,
    SQLITE_DBCONFIG_ENABLE_FKEY = 1002,
    SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003,
    SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004,
    SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005,
    SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006,
    SQLITE_DBCONFIG_ENABLE_QPSG = 1007,
    SQLITE_DBCONFIG_TRIGGER_EQP = 1008,
    SQLITE_DBCONFIG_RESET_DATABASE = 1009,
    SQLITE_DBCONFIG_DEFENSIVE = 1010,
}
